export const SMILESBonds = [
  { name: "Single Bond", structure: "-" },
  { name: "Double Bond", structure: "=" },
  { name: "Triple Bond", structure: "#" },
  { name: "Aromatic Bond", structure: ":" },
  { name: "Disconnected structures", structure: "." },
];

export const SMILESExamples = [
  { name: "Methane (CH4)", structure: "C" },
  { name: "Ethane (CH3CH3)", structure: "CC" },
  { name: "Ethene (CH2CH2)", structure: "C=C" },
  { name: "Ethyne (CHCH)", structure: "C#C" },
  { name: "Hydrogen Cyanide (HCN)", structure: "C#N" },
  { name: "Ethanol (CH3CH2OH)", structure: "CCO" },
  { name: "Acetaldehyde (CH3-CH=O)", structure: "CC=O" },
  { name: "proton", structure: "[H+]" },
  { name: "water", structure: "O" },
  { name: "hydronium cation", structure: "[OH3+]" },
  { name: "carbon dioxide", structure: "O=C=O" },
  { name: "acetic acid", structure: "CC(=O)O" },
  { name: "decalin", structure: "C1CC2CCCCC2CC1" },
  { name: "Benzene (C6H6)", structure: "C1=CC=CC=C1" },
  { name: "sodium phenoxide", structure: "[Na+].[O-]c1ccccc1" },
  { name: "nitrobenzene", structure: "c1ccccc1[N+](=O)[O-]" },
  { name: "trans-2-butene", structure: "C/C=C/C" },
  { name: "cis-resorcinol", structure: "O[C@H]1CCCC[C@H]1O" },
  { name: "biphenyl", structure: "c1ccccc1c2ccccc2" },
  { name: "napthalene", structure: "c12c(cccc1)cccc2" },
  { name: "Dimethyl ether (CH3OCH3)", structure: "COC" },
  { name: "Isobutyl alcohol (CH3-CH(CH3)-CH2-OH)", structure: "CC(C)CO" },
  { name: "Uranium", structure: "[U]" },
  { name: "Lead", structure: "[Pb]" },
  { name: "Helium", structure: "[He]" },
  { name: "chloride anion", structure: "[Cl-]" },
  { name: "hydroxyl anion", structure: "[OH-1]" },
  { name: "copper cation", structure: "[Cu++]" },
  { name: "ammonia", structure: "N" },
  { name: "hydrochloric acid", structure: "Cl" },
  { name: "ortho-substituted phenol", structure: "Oc1c(*)cccc1" },
  { name: "n-butylamine", structure: "NCCCC" },
  { name: "propanol", structure: "CCC=O" },
  { name: "2-butyne", structure: "CC#CC" },
  { name: "2,4-dimethyl-3-pentanone", structure: "CC(C)C(=O)C(C)C" },
  { name: "2-ethyl-1-butanol", structure: "CCC(CC)CO" },
  { name: "cyclohexane", structure: "C1CCCCC1" },
  { name: "cyclohexene", structure: "C=1CCCCC1" },
  { name: "spiro[5.5]undecane", structure: "C12(CCCCC1)CCCCC2" },
  { name: "indane", structure: "c1ccc2CCCc2c1" },
  { name: "furan", structure: "c1occc1" },
  { name: "sodium chloride", structure: "[Na+].[Cl-]" },
  { name: "trans-difluoroethane", structure: "F/C=C/F" },
  { name: "cis-difluoroethane", structure: "FC=C/F" },
];
